# Header
menu:
  首页: /
  前端: categories/front-end
  后端: back-end
  标签: javascript:;
  归档: archives
  订阅: atom.xml
  关于: about

# Content
excerpt_link: 阅读更多

# Sidebar
author:
  name: Sanonz
  work: Web Developer &amp; Designer
  location: Shenzhen, China
  avatar_url: /images/avatar.jpg
# widgets:
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
# index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
# show_count: false
# archive_type: 'monthly'

# Disqus 
disqus:
  enable: true
  shortname: name    #your name
  # count: true

# 友盟统计
umeng:
  prefix: s13
  id: 1234567890

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
